// SPDX-License-Identifier: Apache-2.0 OR MIT
//! FIPS 204 known-answer tests for ML-DSA-65, from NIST's own ACVP vectors.
//!
//! **Why this exists, and why it is not optional.** AINRA's conformance vectors were *generated by* the
//! `ml-dsa` crate. That makes them excellent at catching disagreement *between our four implementations* and
//! completely unable to adjudicate a change *to the crate itself* — if the crate's output moved, the corpus would
//! move with it and every check would still be green. Upgrading `ml-dsa` for RUSTSEC-2025-0144 required ground
//! truth from outside our own toolchain, so this suite compares the crate against NIST.
//!
//! Source: NIST ACVP-Server, `gen-val/json-files/ML-DSA-{keyGen,sigGen,sigVer}-FIPS204/internalProjection.json`
//! (<https://github.com/usnistgov/ACVP-Server>), retrieved 2026-08-06. The extracted subset lives in
//! `vectors/nist/ml-dsa-65-fips204-kat.json` and is limited to the exact profile `ainra-core` uses:
//! **ML-DSA-65, external signature interface, pure (not pre-hash), external-mu off, deterministic**.
//!
//! What each half proves:
//!
//! * `keyGen` — a seed expands to the byte-exact public and secret key NIST specifies.
//! * `sigGen` — deterministic signing over (sk, message, context) produces the byte-exact signature NIST
//!   specifies. This is the strongest form available: not "a valid signature", *the* signature.
//! * `sigVer` — 15 cases, **12 of them negative** (modified z, modified hint, modified commitment, modified
//!   message). A verifier that accepts everything passes the positive cases and fails here.

use ml_dsa::{
    ExpandedSigningKey, ExpandedSigningKeyBytes, MlDsa65, Seed, SigningKey, VerifyingKey,
};

const KAT: &str = include_str!("../../../vectors/nist/ml-dsa-65-fips204-kat.json");

fn hex(s: &str) -> Vec<u8> {
    hex::decode(s).expect("KAT hex")
}

fn kat() -> serde_json::Value {
    serde_json::from_str(KAT).expect("KAT json")
}

/// A seed must expand to exactly the key pair NIST publishes for it.
#[test]
fn fips204_keygen_matches_nist() {
    let j = kat();
    let cases = j["keyGen"].as_array().expect("keyGen");
    assert!(!cases.is_empty(), "KAT file has no keyGen cases");
    for c in cases {
        let tc = c["tcId"].as_u64().unwrap_or(0);
        let seed = hex(c["seed"].as_str().expect("seed"));
        let xi = Seed::try_from(&seed[..]).expect("seed is 32 bytes");
        // `from_seed` IS FIPS 204 Algorithm 6 — the same algorithm 0.0.4 reached through `key_gen_internal`.
        let sk = SigningKey::<MlDsa65>::from_seed(&xi);
        let vk: &VerifyingKey<MlDsa65> = sk.as_ref();
        assert_eq!(
            vk.encode().as_slice(),
            hex(c["pk"].as_str().expect("pk")).as_slice(),
            "tc{tc}: public key differs from NIST"
        );
        // NIST publishes the EXPANDED (Algorithm 24 skEncode) secret key; 0.1 prefers the 32-byte seed form and
        // marks the expanded encoding deprecated, but the encoding itself is still normative and still the thing
        // NIST specifies — so this is exactly where we want to keep checking it.
        #[allow(deprecated)]
        let sk_expanded = sk.expanded_key().to_expanded();
        assert_eq!(
            sk_expanded.as_slice(),
            hex(c["sk"].as_str().expect("sk")).as_slice(),
            "tc{tc}: secret key differs from NIST"
        );
    }
}

/// Deterministic signing must produce the byte-exact signature NIST publishes — not merely a valid one.
#[test]
fn fips204_siggen_matches_nist_byte_for_byte() {
    let j = kat();
    let cases = j["sigGen"].as_array().expect("sigGen");
    assert!(!cases.is_empty(), "KAT file has no sigGen cases");
    for c in cases {
        let tc = c["tcId"].as_u64().unwrap_or(0);
        let sk_bytes = hex(c["sk"].as_str().expect("sk"));
        let enc = ExpandedSigningKeyBytes::<MlDsa65>::try_from(&sk_bytes[..]).expect("sk length");
        #[allow(deprecated)]
        let sk = ExpandedSigningKey::<MlDsa65>::from_expanded(&enc);
        let msg = hex(c["message"].as_str().expect("message"));
        let ctx = hex(c["context"].as_str().unwrap_or(""));
        let sig = sk.sign_deterministic(&msg, &ctx).expect("sign");
        assert_eq!(
            sig.encode().as_slice(),
            hex(c["signature"].as_str().expect("signature")).as_slice(),
            "tc{tc}: signature differs from NIST"
        );
    }
}

/// Verification must agree with NIST on every case — including, especially, the ones that must be REJECTED.
#[test]
fn fips204_sigver_matches_nist_including_negatives() {
    let j = kat();
    let cases = j["sigVer"].as_array().expect("sigVer");
    assert!(!cases.is_empty(), "KAT file has no sigVer cases");
    let mut negatives = 0usize;
    for c in cases {
        let tc = c["tcId"].as_u64().unwrap_or(0);
        let want = c["testPassed"].as_bool().expect("testPassed");
        if !want {
            negatives += 1;
        }
        let reason = c["reason"].as_str().unwrap_or("-");

        let pk_bytes = hex(c["pk"].as_str().expect("pk"));
        let vk = match ml_dsa::EncodedVerifyingKey::<MlDsa65>::try_from(&pk_bytes[..]) {
            Ok(enc) => VerifyingKey::<MlDsa65>::decode(&enc),
            // a malformed key is a refusal, and a refusal is only correct on a negative case
            Err(_) => {
                assert!(
                    !want,
                    "tc{tc}: NIST expects PASS but the public key would not decode"
                );
                continue;
            }
        };
        let msg = hex(c["message"].as_str().expect("message"));
        let ctx = hex(c["context"].as_str().unwrap_or(""));
        let sig_bytes = hex(c["signature"].as_str().expect("signature"));

        let got = match ml_dsa::EncodedSignature::<MlDsa65>::try_from(&sig_bytes[..]) {
            Ok(enc) => match ml_dsa::Signature::<MlDsa65>::decode(&enc) {
                Some(sig) => vk.verify_with_context(&msg, &ctx, &sig),
                None => false, // undecodable signature — fail closed
            },
            Err(_) => false,
        };
        assert_eq!(got, want, "tc{tc} ({reason}): verdict disagrees with NIST");
    }
    // Guard the guard: if a future extraction silently dropped the negatives, this suite would be proving that a
    // verifier which accepts everything is correct.
    assert!(
        negatives >= 10,
        "expected the NIST negative cases (modified z / hint / commitment / message); found only {negatives}"
    );
}
